name: React Low Code Editor

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch  addd
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          # Yarn command
          cmd: install # npm install/ yarn install

      - name: Creating build
        run: sudo yarn build
        env:
          CI: false

      - name: installing surge
        run: npm install -g surge

      - name: deploying on Dev surge
        run: surge ./build https://reacteditor.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
